# Form implementation generated from reading ui file 'upload-gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(322, 305)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uploadBtn.setGeometry(QtCore.QRect(0, 0, 131, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadBtn.sizePolicy().hasHeightForWidth())
        self.uploadBtn.setSizePolicy(sizePolicy)
        self.uploadBtn.setMaximumSize(QtCore.QSize(131, 16777215))
        self.uploadBtn.setAcceptDrops(True)
        self.uploadBtn.setCheckable(False)
        self.uploadBtn.setObjectName("uploadBtn")
        self.uploadBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uploadBtn_2.setGeometry(QtCore.QRect(160, 0, 131, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadBtn_2.sizePolicy().hasHeightForWidth())
        self.uploadBtn_2.setSizePolicy(sizePolicy)
        self.uploadBtn_2.setMaximumSize(QtCore.QSize(131, 16777215))
        self.uploadBtn_2.setAcceptDrops(True)
        self.uploadBtn_2.setCheckable(False)
        self.uploadBtn_2.setObjectName("uploadBtn_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 322, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuSerato_DJ_Analyzer = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSerato_DJ_Analyzer.setObjectName("menuSerato_DJ_Analyzer")
        MainWindow.setMenuBar(self.menuBar)
        self.actionDrop_Setlist = QtGui.QAction(parent=MainWindow)
        self.actionDrop_Setlist.setObjectName("actionDrop_Setlist")
        self.menuBar.addAction(self.menuSerato_DJ_Analyzer.menuAction())

        self.uploadBtn.clicked.connect(self.on_click)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uploadBtn.setText(_translate("MainWindow", "TESTS1"))
        self.uploadBtn_2.setText(_translate("MainWindow", "TESTS2"))
        self.menuSerato_DJ_Analyzer.setTitle(_translate("MainWindow", "Serato DJ Analyzer"))
        self.actionDrop_Setlist.setText(_translate("MainWindow", "Drop Setlist"))

    
    def on_click(self):
        print("KAHGSFGHKASFDHGKADFSHGKDAFGHK")
